# Generated by Django 5.1.1 on 2024-10-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontrak_no', models.CharField(max_length=20)),
                ('client_name', models.CharField(max_length=100)),
                ('harga_mobil', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dp_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tenor_tahun', models.IntegerField()),
                ('bunga_tahunan', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tgl_mulai', models.DateField()),
            ],
        ),
    ]
